### PR TITLE
Add tool SPARQL micro-services

### PR DESCRIPTION
**Pull request by frmichel**

### CODE REVIEW

**Comment by frmichel** [comment]
Sorry mistake, this one was for tools, not for use cases.

**Comment by frmichel** [comment]
I'm definitely confused... this was the right place ;). Sorry about that.

**Comment by dachafra** [comment]
nice to see the contribution @frmichel :-)

**Comment by frmichel** [comment]
> nice to see the contribution @frmichel :-)

And thx to you @dachafra for taking care of all this ;)

**Pull request merged**
